### ISSUE TITLE
Nothing appears

### ISSUE THREAD

**Issue by odyright** [henrychavez/cms-laravel-angular-material#1]
![nthg](https://cloud.githubusercontent.com/assets/4316506/10067518/d4b49c22-628c-11e5-9787-95f929694ecd.JPG)

**Comment by odyright** [comment]
i missed anything?

**Comment by henrychavez** [comment]
you follow all the steps?

2015-09-24 2:21 GMT-05:00 odyright <notifications@github.com>:

> i missed anything?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-142837556>
> .
>



-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by odyright** [comment]
yes:...
1) #fix database credentials in .env
2) npm install
3) gulp && gulp watch
4) php artisan serve

**Comment by henrychavez** [comment]
Check if all dependencies have been downloaded and check your console
browser if any error appears. I recently checked and works fine.

On Thursday, September 24, 2015, odyright <notifications@github.com> wrote:

> yes:...
> 1) #fix database credentials in .env
> 2) npm install
> 3) gulp && gulp watch
> 4) php artisan serve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-142868221>
> .
>


-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by odyright** [comment]
ok let me try

**Comment by jadjoubran** [comment]
Isn't it because you're on the `auth/login` route?

**Comment by odyright** [comment]
Yes i am on the<code>auth/login</code>...

**Comment by jadjoubran** [comment]
Try going to `/` would it work?

**Comment by odyright** [comment]
nothing!

**Comment by jadjoubran** [comment]
Make sure you have APP_DEBUG=true in your `.env` file. 
If you still see a blank page, you need to check your apache/nginx error log

**Comment by henrychavez** [comment]
Jad you don't have problems?

On Thursday, September 24, 2015, Jad Joubran <notifications@github.com>
wrote:

> Make sure you have APP_DEBUG=true in your .env file.
> If you still see a blank page, you need to check your apache/nginx error
> log
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-143050246>
> .
>


-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by jadjoubran** [comment]
I never tried it

**Comment by masterpowers** [comment]
tried to install this im getting same result 
Uncaught TypeError: Cannot read property 'module' of undefined
angular-all.min.js:1 Uncaught ReferenceError: angular is not defined

Must be the Link for Angular Js script

**Comment by henrychavez** [comment]
uhmm You tried running gulp?

2015-10-22 22:04 GMT-05:00 masterpowers <notifications@github.com>:

> tried to install this im getting same result
> Uncaught TypeError: Cannot read property 'module' of undefined
> angular-all.min.js:1 Uncaught ReferenceError: angular is not defined
>
> Must be the Link for Angular Js script
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-150437753>
> .
>



-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by masterpowers** [comment]
yes its running  and working
```
vagrant@homestead:~/Code/pimpmysite2$ gulp && gulp watch
[03:12:06] Using gulpfile ~/Code/pimpmysite2/gulpfile.js
[03:12:06] Starting 'default'...
[03:12:06] Starting 'vendor-js'...
Bundling, minifying, and copying the Angular Vendor JavaScript files
[03:12:07] Finished 'default' after 1.01 s
[03:14:24] angular-vendor.min.js went from 225.97 kB to 225.39 kB and is 0.26% smaller.
[03:14:24] gulp-notify: [Laravel Elixir]
[03:14:24] Finished 'vendor-js' after 2.3 min
[03:14:24] Starting 'vendor-scss'...
[03:14:25] gulp-notify: [Laravel Elixir]
[03:14:25] Finished 'vendor-scss' after 96 ms
[03:14:25] Starting 'sass'...

Fetching Sass Source Files...
   - resources/assets/sass/app.scss


Saving To...
   - public/css/app.css

[03:14:35] gulp-notify: [Laravel Elixir] Sass Compiled!
[03:14:35] Finished 'sass' after 10 s
[03:14:35] Starting 'angular_js'...
Bundling, minifying, and copying the app's JavaScript
[03:14:37] angular-all.min.js went from 32.61 kB to 12.11 kB and is 62.88% smaller.
[03:14:37] gulp-notify: [Laravel Elixir]
[03:14:37] Finished 'angular_js' after 2.45 s
[03:15:07] Using gulpfile ~/Code/pimpmysite2/gulpfile.js
[03:15:07] Starting 'watch'...
[03:15:08] Finished 'watch' after 728 ms
```

**Comment by henrychavez** [comment]
run gulp angular-vendor

or tried *npm install* again, also you can verify if the angular files are
in your node_modules folder

2015-10-22 22:14 GMT-05:00 Henry Chavez V. <henry19.chavez@gmail.com>:

> uhmm You tried running gulp?
>
> 2015-10-22 22:04 GMT-05:00 masterpowers <notifications@github.com>:
>
>> tried to install this im getting same result
>> Uncaught TypeError: Cannot read property 'module' of undefined
>> angular-all.min.js:1 Uncaught ReferenceError: angular is not defined
>>
>> Must be the Link for Angular Js script
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-150437753>
>> .
>>
>
>
>
> --
> Henry G. Chávez Vergara.
> Design, Web & Mobile Development
> Phone: +(51) 944119329
> Email: henry19.chavez@gmail.com
> Lima - Perú
>



-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by masterpowers** [comment]
I got this Task 'angular-vendor' is not in your gulpfile

**Comment by henrychavez** [comment]
yes, sorry it's *vendor-js* but verify the angular files in node_modules If
you do not find the files you need to run *npm install*

2015-10-22 22:20 GMT-05:00 masterpowers <notifications@github.com>:

> I got this Task 'angular-vendor' is not in your gulpfile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-150447139>
> .
>



-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by masterpowers** [comment]
i can run gulp vendor-js

**Comment by henrychavez** [comment]
You have verified that the Angular files are in node_modules?

2015-10-22 22:26 GMT-05:00 masterpowers <notifications@github.com>:

> i can run gulp vendor-js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-150448392>
> .
>



-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by masterpowers** [comment]
yes it is , i got angular-material , angular-messages , angular-route, angular-sanitize
and other stuff not name angular

**Comment by henrychavez** [comment]
I see the problem you don't have angular and maybe it's for your version of
npm

In some versions of npm when you install angular material the angular file
doesn't install automatically

you can try running npm install angular

then you can run gulp vendor-js

2015-10-22 22:30 GMT-05:00 masterpowers <notifications@github.com>:

> yes it is , i got angular-material , angular-messages , angular-route,
> angular-sanitize
> and other stuff not name angular
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-150449016>
> .
>



-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by masterpowers** [comment]
i got latest version of node and npm, thanks ill try it out...
btw you have a guide or sample to work out to get this thing twerking?

**Comment by henrychavez** [comment]
sorry, I dont have a guide yet. I'm kinda busy right now but I'll try to
make one as soon as I can

2015-10-22 22:38 GMT-05:00 masterpowers <notifications@github.com>:

> i got latest version of node and npm, thanks ill try it out...
> btw you have a guide or sample to work out to get this thing twerking?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/1#issuecomment-150451890>
> .
>



-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by masterpowers** [comment]
thanks

**Comment by masterpowers** [comment]
I tried to install angular and got this
```
npm WARN EPEERINVALID angular-material@0.10.1 requires a peer of angular@^1.3.15 || >1.4.0-beta.0 but none was installed.
npm WARN EPEERINVALID angular-material@0.10.1 requires a peer of angular-animate@^1.3.15 || >1.4.0-beta.0 but none was installed.
npm WARN EPEERINVALID angular-material@0.10.1 requires a peer of angular-aria@^1.3.15 || >1.4.0-beta.0 but none was installed.
vagrant@homestead:~/Code/pimpmysite2$ npm install angular
npm WARN install Couldn't install optional dependency: Unsupported
/home/vagrant/Code/pimpmysite2
├── angular@1.4.7  extraneous
├── UNMET PEER DEPENDENCY angular-animate@^1.3.15 || >1.4.0-beta.0
└── UNMET PEER DEPENDENCY angular-aria@^1.3.15 || >1.4.0-beta.0

npm WARN EPEERINVALID angular-material@0.10.1 requires a peer of angular-animate@^1.3.15 || >1.4.0-beta.0 but none was installed.
npm WARN EPEERINVALID angular-material@0.10.1 requires a peer of angular-aria@^1.3.15 || >1.4.0-beta.0 but none was installed.
```

**Comment by masterpowers** [comment]
i run another npm install and it work cheers!

**Comment by odyright** [comment]
@masterpowers did you test that CMS? how it is?
