### ISSUE TITLE
catch return value to views?

### ISSUE THREAD

**Issue by binhbeer** [henrychavez/cms-laravel-angular-material#2]
i can't get any return values from controller.

return view('layouts.' . $this->layout, $data);

how to get $data in views?

**Comment by henrychavez** [comment]
Hi,

You see the laravel documentation? It's the same way

On Friday, October 2, 2015, BinhBEER <notifications@github.com> wrote:

> i can't get any return values from controller.
>
> return view('layouts.' . $this->layout, $data);
>
> how to get $data in views?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/henrychavez/cms-laravel-angular-material/issues/2>.
>


-- 
Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú
